// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdJxre-h0o2gbFfHTwb7XT9nxpYzEeEw',
    appId: '1:1094319730073:web:786b224ec5d63b8caa3708',
    messagingSenderId: '1094319730073',
    projectId: 'practice-9483',
    authDomain: 'practice-9483.firebaseapp.com',
    storageBucket: 'practice-9483.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9Bw92OStnvdukPLmE2uYO7uF3d69Fhc',
    appId: '1:1094319730073:android:82b27342f4bfa455aa3708',
    messagingSenderId: '1094319730073',
    projectId: 'practice-9483',
    storageBucket: 'practice-9483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE2-Y6rj5QR_H-kOKfA_4skGoEY7L0r7s',
    appId: '1:1094319730073:ios:9f5868ef5db71fd6aa3708',
    messagingSenderId: '1094319730073',
    projectId: 'practice-9483',
    storageBucket: 'practice-9483.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE2-Y6rj5QR_H-kOKfA_4skGoEY7L0r7s',
    appId: '1:1094319730073:ios:9f5868ef5db71fd6aa3708',
    messagingSenderId: '1094319730073',
    projectId: 'practice-9483',
    storageBucket: 'practice-9483.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPdJxre-h0o2gbFfHTwb7XT9nxpYzEeEw',
    appId: '1:1094319730073:web:fc55dbc3ebd25db7aa3708',
    messagingSenderId: '1094319730073',
    projectId: 'practice-9483',
    authDomain: 'practice-9483.firebaseapp.com',
    storageBucket: 'practice-9483.appspot.com',
  );
}
